version: "3.3"
volumes:
  mongodbdata:
services:
  client:
    image: node
    working_dir: /code
    volumes:
        - ./client:/code
    command: ["yarn", "start"]
    ports:
    - 3000:3000
  mongodb:
    image: mongo:4.4.6
    container_name: games_mongo
    restart: always
    volumes:
    - mongodbdata:/data/db
    ports:
    - 27017:27017 
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build:
      context: ./lith
      dockerfile: development.dockerfile
    volumes:
    - ./lith:/code
    working_dir: /code
    ports:
    - 8081:8081
    command: ["uvicorn", "serve.api:app", "--host", "0.0.0.0",  "--reload", "--port", "8081"]
