version: "3.9"
services:
  react:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
  # api:
  #   build:
  #     context: ./lith
  #     dockerfile: ./lith/Dockerfile
  #   ports:
  #     - "5000:5000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
